"""empty message

Revision ID: 5fb522270d88
Revises: dc14cb1e6c2c
Create Date: 2019-11-30 14:17:51.686905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb522270d88'
down_revision = 'dc14cb1e6c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'traderid')
    op.drop_column('record', 'user')
    op.drop_column('record', 'trader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('trader', sa.VARCHAR(length=500), nullable=True))
    op.add_column('record', sa.Column('user', sa.VARCHAR(length=500), nullable=True))
    op.add_column('log', sa.Column('traderid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
