"""empty message

Revision ID: 5940a24f6ed3
Revises: dc14cb1e6c2c
Create Date: 2019-12-16 16:26:57.973018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5940a24f6ed3'
down_revision = 'dc14cb1e6c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('goodname', sa.String(length=25), nullable=True))
    op.add_column('log', sa.Column('host', sa.String(length=25), nullable=True))
    op.add_column('log', sa.Column('ip', sa.String(length=25), nullable=True))
    op.add_column('log', sa.Column('mac', sa.String(length=25), nullable=True))
    op.add_column('log', sa.Column('username', sa.String(length=25), nullable=True))
    op.drop_column('log', 'goodid')
    op.drop_column('log', 'traderid')
    op.drop_column('log', 'userid')
    op.drop_column('record', 'user')
    op.drop_column('record', 'trader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('trader', sa.VARCHAR(length=500), nullable=True))
    op.add_column('record', sa.Column('user', sa.VARCHAR(length=500), nullable=True))
    op.add_column('log', sa.Column('userid', sa.INTEGER(), nullable=True))
    op.add_column('log', sa.Column('traderid', sa.INTEGER(), nullable=True))
    op.add_column('log', sa.Column('goodid', sa.INTEGER(), nullable=True))
    op.drop_column('log', 'username')
    op.drop_column('log', 'mac')
    op.drop_column('log', 'ip')
    op.drop_column('log', 'host')
    op.drop_column('log', 'goodname')
    # ### end Alembic commands ###
